version: "3.7"

networks:
    nginx-reverse-proxy-manager-network:
        name: nginx-reverse-proxy-manager-network
        external: true
        driver: bridge

volumes:
    db_data:

services:
    web:
        image: nginx:1.19-alpine
        container_name: domain-redirect-nginx
        hostname: domain-redirect-nginx
        expose:
            - 80
        networks:
            - nginx-reverse-proxy-manager-network
        volumes:
            - "./configs:/etc/nginx/templates/"
        restart: always
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        environment:
            NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".nginx-template"
            DESTINATION_URL: https://reparchive.com/feed/top 
