version: "3.7"

networks:
    nelson-net:
        name: nelson-net
        driver: bridge
    chwd-network:
        name: chwd-network
        external: true
        driver: bridge

volumes:
    db_data:

services:
    web:
        image: nginx:latest
        container_name: taobot-nginx
        hostname: taobot-nginx
        # expose:
            # - 94
        ports:
            - 94:80
        networks:
            - nelson-net
            - chwd-network
        volumes:
            - "./html:/var/www/"
            - "./configs/site.conf:/etc/nginx/conf.d/default.conf"
            - "./configs/nginx.conf:/etc/nginx/nginx.conf"
            - "./configs/bots.d/:/etc/nginx/bots.d/"
            - "./configs/globalblacklist.conf:/etc/nginx/conf.d/globalblacklist.conf"
            - "./configs/botblocker-nginx-settings.conf:/etc/nginx/conf.d/botblocker-nginx-settings.conf"
        restart: always
        depends_on:
            - database
        labels:
          - "com.centurylinklabs.watchtower.enable=true"
        # command:
        #   - -c 'mkdir -p /var/www/writable'
        #   - -c 'chmod -R 0777 /var/www/writable'