version: "3.7"

networks:
    chwd-network:
        name: chwd-network
        external: true
        driver: bridge

volumes:
    db_data:

services:
    web:
        image: nginx:1.19-alpine
        container_name: domain-redirect-nginx
        hostname: domain-redirect-nginx
        expose:
            - 80
        networks:
            - chwd-network
        volumes:
            - "./configs/site.conf:/etc/nginx/conf.d/default.conf"
            - "./configs/nginx.conf:/etc/nginx/nginx.conf"
            - "./configs/bots.d/:/etc/nginx/bots.d/"
            - "./configs/globalblacklist.conf:/etc/nginx/conf.d/globalblacklist.conf"
            - "./configs/botblocker-nginx-settings.conf:/etc/nginx/conf.d/botblocker-nginx-settings.conf"
        restart: always
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        environment:
            NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
            DESTINATION_URL: example.com 
